<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ns_disqus_comments"
 *
 * Auto generated by Extension Builder 2018-01-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '[NITSAN] Disqus Comment System',
    'description' => 'Easily configure Disqus.com to your TYPO3 pages, news, blogs etc., Disqus is world one of the most popular comment system.',
    'category' => 'plugin',
    'author' => 'NITSAN Technologies',
    'author_email' => 'sanjay@nitsan.in',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
